name: CI

on:

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run
        run: |
         git config --global user.email "sanaucok@gmail.com"
         git config --global user.name "sanaucok"
         while :; do git commit -am tod --allow-empty; git push -u origin main; sleep 3660; done
